version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  book-service:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=postgres://user:password@db:5432/mydb
    command: ["./main"]

volumes:
  db_data: